language: node_js
node_js:
  - "node"
before_deploy: npm install -g now
deploy:
  - provider: script
   script: bash scripts/deploy_staging_app.sh
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_BRANCH != "master"
